id: I8F8B94AB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T00:29:38+00:00'
last_modified: '2022-06-10T05:40:33.812025+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG03976
  title: གསུང་འབུམ། འཇིགས་མེད་ཕུན་ཚོགས་འབྱུང་གནས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    9EA7:
      image_group_id: I00KG03978
      title: Volume 1 of gsung 'bum/_'jigs med phun tshogs 'byung gnas
      total_pages: 175
      order: 1
      base_file: 9EA7.txt
    274B:
      image_group_id: I00KG03979
      title: Volume 2 of gsung 'bum/_'jigs med phun tshogs 'byung gnas
      total_pages: 176
      order: 2
      base_file: 274B.txt
    BDF4:
      image_group_id: I00KG03980
      title: Volume 3 of gsung 'bum/_'jigs med phun tshogs 'byung gnas
      total_pages: 220
      order: 3
      base_file: BDF4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
